FROM alpine

RUN apk --update --no-cache add bash \
 sudo \
 vim \
 shadow \
  php7 \
   php7-bcmath \
    php7-cli \
    php7-ctype \
    php7-curl \
    php7-dom \
    php7-fpm \
    php7-gd \
    php7-iconv \
    php7-intl \
    php7-json \
    php7-mbstring \
    php7-mcrypt \
    php7-openssl \
    php7-pdo \
    php7-pdo_mysql \
     php7-mysqlnd \
     php7-pdo_sqlite \
     php7-pdo_pgsql \
     php7-phar \
     php7-session \
     php7-simplexml \
     php7-soap \
      php7-tokenizer \
      php7-xml \
      php7-xmlwriter \
       php7-posix \
       php7-xsl \
        php7-zip \
        php7-zlib \
         php7-sockets \
          php7-mysqli \
          php-sodium \
          netcat-openbsd \
          nano \
          curl \
          nginx \
          su-exec \
          util-linux \
          coreutils \
           git \
           gnupg \
            ca-certificates \
            openssl \
             tar \
              unzip \
              wget \
              vim \
              redis \
              bind-tools \
              varnish \
              mysql \
              mysql-client \
              mariadb-server-utils \
              openjdk11 \
              xz \
              erlang \
              rabbitmq-c-dev \
               phpmyadmin \
               openssh \
               openssh-client &&\

addgroup mysql mysql &&\

mkdir /etc/nginx/sites-available &&\
mkdir /etc/nginx/sites-enabled/ &&\
mkdir -p /run/nginx &&\
ln -s /etc/nginx/sites-available/default.conf /etc/nginx/sites-enabled/default.conf &&\
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" HASH="$(wget -q -O - https://composer.github.io/installer.sig)" php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" &&\
php composer-setup.php --install-dir=/usr/local/bin --filename=composer &&\

curl -fSL 'http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz' -o ioncube.tar.gz &&\
tar -xf ioncube.tar.gz &&\
rm ioncube.tar.gz &&\
mv ioncube/ioncube_loader_lin_7.4.so /var/www/ioncube_loader_lin_7.4.so &&\
echo "zend_extension = /var/www/ioncube_loader_lin_7.4.so" >> /etc/php7/php.ini &&\
mkdir -p /var/run/sshd &&\
adduser magento -D -g 1000 &&\
echo  "magento ALL=(ALL) ALL" >> /etc/sudoers &&\
echo "magento:magento" |chpasswd &&\
mkdir  ~/.ssh &&\
ssh-keygen -t rsa -f /root/.ssh/id_rsa -q -P "" &&\
touch ~/.ssh/authorized_keys &&\
chmod -R 600 ~/.ssh/* &&\
echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config &&\
chown -R magento:magento ~/.ssh &&\
chmod -R 700 ~/.ssh &&\
rm -rf /etc/ssh/ssh_host_rsa_key /etc/ssh/ssh_host_dsa_key /etc/ssh/ssh_host_rsa_key.pub /etc/ssh/ssh_host_dsa_key.pub &&\
ssh-keygen -A &&\
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk &&\
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.8.0-linux-x86_64.tar.gz &&\
tar -xvf elasticsearch-7.8.0-linux-x86_64.tar.gz &&\
mv /elasticsearch-7.8.0 /elasticsearch &&\
rm -rf elasticsearch-7.8.0-linux-x86_64.tar.gz &&\
mv /elasticsearch /usr/share/ &&\
adduser -D elasticsearch -g 1000 -h /usr/share/elasticsearch &&\
mkdir -p /usr/share/elasticsearch/data &&\
mkdir -p /usr/share/elasticsearch/tmp &&\
mkdir -p /usr/share/elasticsearch/config/scripts &&\
rm -rf /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64 &&\
export ES_JAVA_HOME=/usr/lib/jvm/java-11-openjdk &&\
export ES_JAVA_OPTS="$ES_JAVA_OPTS -Djava.io.tmpdir=/usr/share/elasticsearch/tmp" &&\
chown -R elasticsearch:elasticsearch /usr/share/elasticsearch &&\
chown -R elasticsearch:elasticsearch /usr/lib/jvm &&\
rm -rf /tmp/* /var/cache/apk/* &&\
echo "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk" >> /etc/profile

COPY redis.conf /etc/ 
COPY sshd_config /etc/ssh/
COPY php.ini /etc/php7/
COPY di.xml /
COPY startup.sh /
COPY default.conf /etc/nginx/sites-available/
COPY nginx.conf /etc/nginx/
COPY my.cnf /etc/mysql/
COPY www.conf /etc/php7/php-fpm.d/
COPY auth.json /root/.composer/
COPY elasticsearch.yml /usr/share/elasticsearch/config/
COPY jvm.options /usr/share/elasticsearch/config/
COPY logrotate /etc/logrotate.d/elasticsearch
COPY default.vcl /etc/varnish/
COPY varnish /etc/default/
COPY phpinfo.php /var/www/html/
WORKDIR /var/www/html/magento
ENTRYPOINT ["/startup.sh"]
EXPOSE 5672 15672 4369 9200 80 443 6379 8888 6082 3306 9000 22
